### PR TITLE
ui(refactor): migrate refine controls to shadcn

### PR DESCRIPTION
**Pull request by ImJustChew**
- Fully migrated refine controls component to shadcn

### CODE REVIEW

**Comment by ImJustChew** [comment]
image

**Comment by ImJustChew** [comment]
Closes #158

**Comment by Joshimello** [comment]
What building issue?

**Comment by ImJustChew** [comment]
Needs merge with latest main branch

Regards,
Chew Tzi Hwee

**Comment by ImJustChew** [comment]
superceded by #229

**Pull request closed without merging**
