### PR TITLE
Route for scraping course data from 10810 ~ 11110 semester

### PR DESCRIPTION
**Pull request by 3normousz**

### CODE REVIEW

**Comment by ImJustChew** [comment]
image
I've realised that the times are concatenated together, is It possible to separate them? Ideally chunks of times should be independent of each other.

**Comment by ImJustChew** [comment]
Thanks @3normousz I've already imported courses 10810~ 11020. However it seems like there are some issues with 11110, could you look into it? 

```
details: 'Failing row contains (, , , , NaN, , , null, null, 0, 中,  , , , , , , f, {}, {}, {""}, {}, {}, {}, {}, {}, {}, {}).
```

**Comment by 3normousz** [comment]
> Thanks @3normousz I've already imported courses 10810~ 11020. However it seems like there are some issues with 11110, could you look into it?
> 
> ```
> details: 'Failing row contains (, , , , NaN, , , null, null, 0, 中,  , , , , , , f, {}, {}, {""}, {}, {}, {}, {}, {}, {}, {}).
> ```

There are some courses in the DL department that are just blank rows, so I skipped when course_id === "". I think it's ok now

**Comment by ImJustChew** [comment]
closes #278

**Pull request closed without merging**
