### PR TITLE
feat: add bottom nav, restyle calendar alert

### PR DESCRIPTION
**Pull request by Joshimello**

### CODE REVIEW

**Comment by ImJustChew** [comment]
image
on /courses styling went wrong

image
White Bar in Dark Mode

image
Should have padding with respect to top viewport (iPhones notch needs that padding)

**Comment by Joshimello** [comment]
> Should have padding with respect to top viewport (iPhones notch needs that padding)

do iphone notches block the viewport?
image

**Comment by ImJustChew** [comment]
https://stackoverflow.com/questions/46354349/iphone-x-website-safe-area

**Comment by ImJustChew** [comment]
https://github.com/nthumodifications/courseweb/assets/17233431/eba96fa0-3c5d-4499-a486-b7bc0aa44865

Bottom nav will block content

**Comment by ImJustChew** [comment]
Bottom nav text needs to be unselectable

**Pull request merged**
